/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "tpu_logic_sram_top" *)
(* top =  1  *)
(* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:1.1-86.10" *)
module tpu_logic_sram_top(clk, rst_n, debug_out);
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:3.11-3.16" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:5.19-5.28" *)
  output [31:0] debug_out;
  wire [31:0] debug_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[0] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[10] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[11] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[12] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[13] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[14] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[15] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[16] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[17] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[18] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[19] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[1] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[20] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[21] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[22] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[23] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[24] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[25] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[26] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[27] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[28] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[29] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[2] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[30] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[31] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[3] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[4] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[5] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[6] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[7] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[8] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:13.13-13.18" *)
  wire \dout0[9] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[0] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[10] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[11] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[12] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[13] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[14] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[15] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[16] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[17] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[18] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[19] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[1] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[20] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[21] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[22] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[23] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[24] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[25] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[26] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[27] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[28] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[29] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[2] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[30] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[31] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[3] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[4] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[5] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[6] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[7] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[8] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:14.13-14.18" *)
  wire \dout1[9] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[0] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[10] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[11] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[12] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[13] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[14] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[15] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[16] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[17] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[18] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[19] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[1] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[20] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[21] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[22] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[23] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[24] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[25] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[26] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[27] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[28] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[29] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[2] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[30] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[31] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[3] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[4] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[5] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[6] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[7] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[8] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:15.13-15.18" *)
  wire \dout2[9] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[0] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[10] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[11] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[12] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[13] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[14] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[15] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[16] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[17] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[18] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[19] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[1] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[20] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[21] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[22] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[23] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[24] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[25] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[26] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[27] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[28] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[29] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[2] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[30] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[31] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[3] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[4] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[5] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[6] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[7] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[8] ;
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:16.13-16.18" *)
  wire \dout3[9] ;
  XOR2_X1 _066_ (
    .A(\dout0[30] ),
    .B(\dout1[30] ),
    .Z(_000_)
  );
  XNOR2_X1 _067_ (
    .A(\dout3[30] ),
    .B(\dout2[30] ),
    .ZN(_001_)
  );
  XNOR2_X1 _068_ (
    .A(_000_),
    .B(_001_),
    .ZN(debug_out[30])
  );
  XOR2_X1 _069_ (
    .A(\dout0[28] ),
    .B(\dout1[28] ),
    .Z(_002_)
  );
  XNOR2_X1 _070_ (
    .A(\dout3[28] ),
    .B(\dout2[28] ),
    .ZN(_003_)
  );
  XNOR2_X1 _071_ (
    .A(_002_),
    .B(_003_),
    .ZN(debug_out[28])
  );
  XOR2_X1 _072_ (
    .A(\dout0[27] ),
    .B(\dout1[27] ),
    .Z(_004_)
  );
  XNOR2_X1 _073_ (
    .A(\dout3[27] ),
    .B(\dout2[27] ),
    .ZN(_005_)
  );
  XNOR2_X1 _074_ (
    .A(_004_),
    .B(_005_),
    .ZN(debug_out[27])
  );
  XOR2_X1 _075_ (
    .A(\dout0[26] ),
    .B(\dout1[26] ),
    .Z(_006_)
  );
  XNOR2_X1 _076_ (
    .A(\dout3[26] ),
    .B(\dout2[26] ),
    .ZN(_007_)
  );
  XNOR2_X1 _077_ (
    .A(_006_),
    .B(_007_),
    .ZN(debug_out[26])
  );
  XOR2_X1 _078_ (
    .A(\dout0[25] ),
    .B(\dout1[25] ),
    .Z(_008_)
  );
  XNOR2_X1 _079_ (
    .A(\dout3[25] ),
    .B(\dout2[25] ),
    .ZN(_009_)
  );
  XNOR2_X1 _080_ (
    .A(_008_),
    .B(_009_),
    .ZN(debug_out[25])
  );
  XOR2_X1 _081_ (
    .A(\dout0[24] ),
    .B(\dout1[24] ),
    .Z(_010_)
  );
  XNOR2_X1 _082_ (
    .A(\dout3[24] ),
    .B(\dout2[24] ),
    .ZN(_011_)
  );
  XNOR2_X1 _083_ (
    .A(_010_),
    .B(_011_),
    .ZN(debug_out[24])
  );
  XOR2_X1 _084_ (
    .A(\dout0[23] ),
    .B(\dout1[23] ),
    .Z(_012_)
  );
  XNOR2_X1 _085_ (
    .A(\dout3[23] ),
    .B(\dout2[23] ),
    .ZN(_013_)
  );
  XNOR2_X1 _086_ (
    .A(_012_),
    .B(_013_),
    .ZN(debug_out[23])
  );
  XOR2_X1 _087_ (
    .A(\dout0[22] ),
    .B(\dout1[22] ),
    .Z(_014_)
  );
  XNOR2_X1 _088_ (
    .A(\dout3[22] ),
    .B(\dout2[22] ),
    .ZN(_015_)
  );
  XNOR2_X1 _089_ (
    .A(_014_),
    .B(_015_),
    .ZN(debug_out[22])
  );
  XOR2_X1 _090_ (
    .A(\dout0[21] ),
    .B(\dout1[21] ),
    .Z(_016_)
  );
  XNOR2_X1 _091_ (
    .A(\dout3[21] ),
    .B(\dout2[21] ),
    .ZN(_017_)
  );
  XNOR2_X1 _092_ (
    .A(_016_),
    .B(_017_),
    .ZN(debug_out[21])
  );
  XOR2_X1 _093_ (
    .A(\dout0[20] ),
    .B(\dout1[20] ),
    .Z(_018_)
  );
  XNOR2_X1 _094_ (
    .A(\dout3[20] ),
    .B(\dout2[20] ),
    .ZN(_019_)
  );
  XNOR2_X1 _095_ (
    .A(_018_),
    .B(_019_),
    .ZN(debug_out[20])
  );
  XOR2_X1 _096_ (
    .A(\dout0[19] ),
    .B(\dout1[19] ),
    .Z(_020_)
  );
  XNOR2_X1 _097_ (
    .A(\dout3[19] ),
    .B(\dout2[19] ),
    .ZN(_021_)
  );
  XNOR2_X1 _098_ (
    .A(_020_),
    .B(_021_),
    .ZN(debug_out[19])
  );
  XOR2_X1 _099_ (
    .A(\dout0[18] ),
    .B(\dout1[18] ),
    .Z(_022_)
  );
  XNOR2_X1 _100_ (
    .A(\dout3[18] ),
    .B(\dout2[18] ),
    .ZN(_023_)
  );
  XNOR2_X1 _101_ (
    .A(_022_),
    .B(_023_),
    .ZN(debug_out[18])
  );
  XOR2_X1 _102_ (
    .A(\dout0[17] ),
    .B(\dout1[17] ),
    .Z(_024_)
  );
  XNOR2_X1 _103_ (
    .A(\dout3[17] ),
    .B(\dout2[17] ),
    .ZN(_025_)
  );
  XNOR2_X1 _104_ (
    .A(_024_),
    .B(_025_),
    .ZN(debug_out[17])
  );
  XOR2_X1 _105_ (
    .A(\dout0[16] ),
    .B(\dout1[16] ),
    .Z(_026_)
  );
  XNOR2_X1 _106_ (
    .A(\dout3[16] ),
    .B(\dout2[16] ),
    .ZN(_027_)
  );
  XNOR2_X1 _107_ (
    .A(_026_),
    .B(_027_),
    .ZN(debug_out[16])
  );
  XOR2_X1 _108_ (
    .A(\dout0[15] ),
    .B(\dout1[15] ),
    .Z(_028_)
  );
  XNOR2_X1 _109_ (
    .A(\dout3[15] ),
    .B(\dout2[15] ),
    .ZN(_029_)
  );
  XNOR2_X1 _110_ (
    .A(_028_),
    .B(_029_),
    .ZN(debug_out[15])
  );
  XOR2_X1 _111_ (
    .A(\dout0[14] ),
    .B(\dout1[14] ),
    .Z(_030_)
  );
  XNOR2_X1 _112_ (
    .A(\dout3[14] ),
    .B(\dout2[14] ),
    .ZN(_031_)
  );
  XNOR2_X1 _113_ (
    .A(_030_),
    .B(_031_),
    .ZN(debug_out[14])
  );
  XOR2_X1 _114_ (
    .A(\dout0[13] ),
    .B(\dout1[13] ),
    .Z(_032_)
  );
  XNOR2_X1 _115_ (
    .A(\dout3[13] ),
    .B(\dout2[13] ),
    .ZN(_033_)
  );
  XNOR2_X1 _116_ (
    .A(_032_),
    .B(_033_),
    .ZN(debug_out[13])
  );
  XOR2_X1 _117_ (
    .A(\dout0[12] ),
    .B(\dout1[12] ),
    .Z(_034_)
  );
  XNOR2_X1 _118_ (
    .A(\dout3[12] ),
    .B(\dout2[12] ),
    .ZN(_035_)
  );
  XNOR2_X1 _119_ (
    .A(_034_),
    .B(_035_),
    .ZN(debug_out[12])
  );
  XOR2_X1 _120_ (
    .A(\dout0[11] ),
    .B(\dout1[11] ),
    .Z(_036_)
  );
  XNOR2_X1 _121_ (
    .A(\dout3[11] ),
    .B(\dout2[11] ),
    .ZN(_037_)
  );
  XNOR2_X1 _122_ (
    .A(_036_),
    .B(_037_),
    .ZN(debug_out[11])
  );
  XOR2_X1 _123_ (
    .A(\dout0[10] ),
    .B(\dout1[10] ),
    .Z(_038_)
  );
  XNOR2_X1 _124_ (
    .A(\dout3[10] ),
    .B(\dout2[10] ),
    .ZN(_039_)
  );
  XNOR2_X1 _125_ (
    .A(_038_),
    .B(_039_),
    .ZN(debug_out[10])
  );
  XOR2_X1 _126_ (
    .A(\dout0[9] ),
    .B(\dout1[9] ),
    .Z(_040_)
  );
  XNOR2_X1 _127_ (
    .A(\dout3[9] ),
    .B(\dout2[9] ),
    .ZN(_041_)
  );
  XNOR2_X1 _128_ (
    .A(_040_),
    .B(_041_),
    .ZN(debug_out[9])
  );
  XOR2_X1 _129_ (
    .A(\dout0[8] ),
    .B(\dout1[8] ),
    .Z(_042_)
  );
  XNOR2_X1 _130_ (
    .A(\dout3[8] ),
    .B(\dout2[8] ),
    .ZN(_043_)
  );
  XNOR2_X1 _131_ (
    .A(_042_),
    .B(_043_),
    .ZN(debug_out[8])
  );
  XOR2_X1 _132_ (
    .A(\dout0[7] ),
    .B(\dout1[7] ),
    .Z(_044_)
  );
  XNOR2_X1 _133_ (
    .A(\dout3[7] ),
    .B(\dout2[7] ),
    .ZN(_045_)
  );
  XNOR2_X1 _134_ (
    .A(_044_),
    .B(_045_),
    .ZN(debug_out[7])
  );
  XOR2_X1 _135_ (
    .A(\dout0[6] ),
    .B(\dout1[6] ),
    .Z(_046_)
  );
  XNOR2_X1 _136_ (
    .A(\dout3[6] ),
    .B(\dout2[6] ),
    .ZN(_047_)
  );
  XNOR2_X1 _137_ (
    .A(_046_),
    .B(_047_),
    .ZN(debug_out[6])
  );
  XOR2_X1 _138_ (
    .A(\dout0[5] ),
    .B(\dout1[5] ),
    .Z(_048_)
  );
  XNOR2_X1 _139_ (
    .A(\dout3[5] ),
    .B(\dout2[5] ),
    .ZN(_049_)
  );
  XNOR2_X1 _140_ (
    .A(_048_),
    .B(_049_),
    .ZN(debug_out[5])
  );
  XOR2_X1 _141_ (
    .A(\dout0[4] ),
    .B(\dout1[4] ),
    .Z(_050_)
  );
  XNOR2_X1 _142_ (
    .A(\dout3[4] ),
    .B(\dout2[4] ),
    .ZN(_051_)
  );
  XNOR2_X1 _143_ (
    .A(_050_),
    .B(_051_),
    .ZN(debug_out[4])
  );
  XOR2_X1 _144_ (
    .A(\dout0[3] ),
    .B(\dout1[3] ),
    .Z(_052_)
  );
  XNOR2_X1 _145_ (
    .A(\dout3[3] ),
    .B(\dout2[3] ),
    .ZN(_053_)
  );
  XNOR2_X1 _146_ (
    .A(_052_),
    .B(_053_),
    .ZN(debug_out[3])
  );
  XOR2_X1 _147_ (
    .A(\dout0[2] ),
    .B(\dout1[2] ),
    .Z(_054_)
  );
  XNOR2_X1 _148_ (
    .A(\dout3[2] ),
    .B(\dout2[2] ),
    .ZN(_055_)
  );
  XNOR2_X1 _149_ (
    .A(_054_),
    .B(_055_),
    .ZN(debug_out[2])
  );
  XOR2_X1 _150_ (
    .A(\dout0[1] ),
    .B(\dout1[1] ),
    .Z(_056_)
  );
  XNOR2_X1 _151_ (
    .A(\dout3[1] ),
    .B(\dout2[1] ),
    .ZN(_057_)
  );
  XNOR2_X1 _152_ (
    .A(_056_),
    .B(_057_),
    .ZN(debug_out[1])
  );
  XOR2_X1 _153_ (
    .A(\dout0[0] ),
    .B(\dout1[0] ),
    .Z(_058_)
  );
  XNOR2_X1 _154_ (
    .A(\dout3[0] ),
    .B(\dout2[0] ),
    .ZN(_059_)
  );
  XNOR2_X1 _155_ (
    .A(_058_),
    .B(_059_),
    .ZN(debug_out[0])
  );
  XOR2_X1 _156_ (
    .A(\dout2[31] ),
    .B(\dout3[31] ),
    .Z(_060_)
  );
  XNOR2_X1 _157_ (
    .A(\dout0[31] ),
    .B(\dout1[31] ),
    .ZN(_061_)
  );
  XNOR2_X1 _158_ (
    .A(_060_),
    .B(_061_),
    .ZN(debug_out[31])
  );
  XOR2_X1 _159_ (
    .A(\dout1[29] ),
    .B(\dout3[29] ),
    .Z(_062_)
  );
  XNOR2_X1 _160_ (
    .A(\dout2[29] ),
    .B(\dout0[29] ),
    .ZN(_063_)
  );
  XNOR2_X1 _161_ (
    .A(_062_),
    .B(_063_),
    .ZN(debug_out[29])
  );
  LOGIC1_X1 _162_ (
    .Z(_064_)
  );
  LOGIC0_X1 _163_ (
    .Z(_065_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:25.17-33.2" *)
  SRAM_32x128_1rw mem0 (
    .addr0({ _065_, _065_, _065_, _065_, _065_, _065_, _065_ }),
    .clk0(clk),
    .csb0(_065_),
    .din0({ _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_ }),
    .dout0({ \dout0[31] , \dout0[30] , \dout0[29] , \dout0[28] , \dout0[27] , \dout0[26] , \dout0[25] , \dout0[24] , \dout0[23] , \dout0[22] , \dout0[21] , \dout0[20] , \dout0[19] , \dout0[18] , \dout0[17] , \dout0[16] , \dout0[15] , \dout0[14] , \dout0[13] , \dout0[12] , \dout0[11] , \dout0[10] , \dout0[9] , \dout0[8] , \dout0[7] , \dout0[6] , \dout0[5] , \dout0[4] , \dout0[3] , \dout0[2] , \dout0[1] , \dout0[0]  }),
    .web0(_064_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:35.17-43.2" *)
  SRAM_32x128_1rw mem1 (
    .addr0({ _065_, _065_, _065_, _065_, _065_, _065_, _065_ }),
    .clk0(clk),
    .csb0(_065_),
    .din0({ _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_ }),
    .dout0({ \dout1[31] , \dout1[30] , \dout1[29] , \dout1[28] , \dout1[27] , \dout1[26] , \dout1[25] , \dout1[24] , \dout1[23] , \dout1[22] , \dout1[21] , \dout1[20] , \dout1[19] , \dout1[18] , \dout1[17] , \dout1[16] , \dout1[15] , \dout1[14] , \dout1[13] , \dout1[12] , \dout1[11] , \dout1[10] , \dout1[9] , \dout1[8] , \dout1[7] , \dout1[6] , \dout1[5] , \dout1[4] , \dout1[3] , \dout1[2] , \dout1[1] , \dout1[0]  }),
    .web0(_064_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:45.17-53.2" *)
  SRAM_32x128_1rw mem2 (
    .addr0({ _065_, _065_, _065_, _065_, _065_, _065_, _065_ }),
    .clk0(clk),
    .csb0(_065_),
    .din0({ _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_ }),
    .dout0({ \dout2[31] , \dout2[30] , \dout2[29] , \dout2[28] , \dout2[27] , \dout2[26] , \dout2[25] , \dout2[24] , \dout2[23] , \dout2[22] , \dout2[21] , \dout2[20] , \dout2[19] , \dout2[18] , \dout2[17] , \dout2[16] , \dout2[15] , \dout2[14] , \dout2[13] , \dout2[12] , \dout2[11] , \dout2[10] , \dout2[9] , \dout2[8] , \dout2[7] , \dout2[6] , \dout2[5] , \dout2[4] , \dout2[3] , \dout2[2] , \dout2[1] , \dout2[0]  }),
    .web0(_064_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/ivann/OpenROAD-flow-scripts/flow/designs/nangate45/tpu_logic_sram/top.v:55.17-63.2" *)
  SRAM_32x128_1rw mem3 (
    .addr0({ _065_, _065_, _065_, _065_, _065_, _065_, _065_ }),
    .clk0(clk),
    .csb0(_065_),
    .din0({ _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_ }),
    .dout0({ \dout3[31] , \dout3[30] , \dout3[29] , \dout3[28] , \dout3[27] , \dout3[26] , \dout3[25] , \dout3[24] , \dout3[23] , \dout3[22] , \dout3[21] , \dout3[20] , \dout3[19] , \dout3[18] , \dout3[17] , \dout3[16] , \dout3[15] , \dout3[14] , \dout3[13] , \dout3[12] , \dout3[11] , \dout3[10] , \dout3[9] , \dout3[8] , \dout3[7] , \dout3[6] , \dout3[5] , \dout3[4] , \dout3[3] , \dout3[2] , \dout3[1] , \dout3[0]  }),
    .web0(_064_)
  );
endmodule
